import * as THREE from "three";

const UP = new THREE.Vector3(0, 1, 0);
const ZERO = new THREE.Vector3();
const clamp01 = (value) => THREE.MathUtils.clamp(value, 0, 1);
const smooth = (value) => value * value * (3 - 2 * value);

export class MissileSystem {
  constructor({ scene, obstacles, target, launcher, config, onHit, onMessage }) {
    this.scene = scene; this.obstacles = obstacles; this.target = target; this.launcher = launcher; this.config = config; this.onHit = onHit; this.onMessage = onMessage;
    this.active = []; this.pool = []; this.volley = null; this.seed = 1337; this.time = 0; this.raycaster = new THREE.Raycaster();
    this.bodyGeometry = new THREE.ConeGeometry(0.13, 0.62, 5); this.exhaustGeometry = new THREE.ConeGeometry(0.075, 0.22, 5);
    this.bodyMaterial = new THREE.MeshBasicMaterial({ color: 0xffb13b }); this.exhaustMaterial = new THREE.MeshBasicMaterial({ color: 0xfff0a0 });
    this.trailMaterial = new THREE.LineBasicMaterial({ color: 0xff9c42, transparent: true, opacity: this.config.trailOpacity, depthWrite: false });
    this.debugGroup = new THREE.Group(); scene.add(this.debugGroup);
    this.ensurePool();
  }
  random() { this.seed = (this.seed * 1664525 + 1013904223) >>> 0; return this.seed / 4294967296; }
  ensurePool() {
    while (this.pool.length < Math.max(8, Math.floor(this.config.maxActiveMissiles))) {
      const root = new THREE.Group(); const body = new THREE.Mesh(this.bodyGeometry, this.bodyMaterial); body.rotation.x = Math.PI / 2; const exhaust = new THREE.Mesh(this.exhaustGeometry, this.exhaustMaterial); exhaust.position.z = 0.38; exhaust.rotation.x = -Math.PI / 2; root.add(body, exhaust);
      const maxPoints = 96; const geometry = new THREE.BufferGeometry(); geometry.setAttribute("position", new THREE.BufferAttribute(new Float32Array(maxPoints * 3), 3)); geometry.setDrawRange(0, 0); const line = new THREE.Line(geometry, this.trailMaterial); root.add(line);
      const arrows = [new THREE.ArrowHelper(new THREE.Vector3(0, 0, 1), ZERO, 2, 0x72c7ff), new THREE.ArrowHelper(new THREE.Vector3(0, 0, 1), ZERO, 2, 0xffe477), new THREE.ArrowHelper(new THREE.Vector3(0, 0, 1), ZERO, 2, 0xff6b91)]; arrows.forEach((arrow) => this.debugGroup.add(arrow));
      root.visible = false; this.scene.add(root); this.pool.push({ root, body, exhaust, line, history: Array.from({ length: maxPoints }, () => new THREE.Vector3()), direction: new THREE.Vector3(), velocity: new THREE.Vector3(), spread: new THREE.Vector3(), curlAxis: new THREE.Vector3(), targetVector: new THREE.Vector3(), desired: new THREE.Vector3(), curl: new THREE.Vector3(), previous: new THREE.Vector3(), age: 0, sampleTimer: 0, delay: 0, life: 0, arrows, active: false });
    }
  }
  activate() {
    const missile = this.pool.find((item) => !item.active); if (!missile) return null; missile.active = true; missile.root.visible = this.config.showMissiles; missile.root.scale.setScalar(this.config.missileScale); this.active.push(missile); return missile;
  }
  fireVolley() {
    if (this.volley || !this.launcher || !this.target) return false; this.ensurePool(); const count = Math.min(128, Math.max(1, Math.floor(this.config.missileCount))); this.volley = { next: 0, timer: 0, count }; this.onMessage?.(`SWARM VOLLEY: ${count}`); return true;
  }
  clear() { this.active.forEach((missile) => this.release(missile)); this.active.length = 0; this.volley = null; }
  release(missile) { missile.active = false; missile.root.visible = false; missile.line.geometry.setDrawRange(0, 0); missile.arrows.forEach((arrow) => { arrow.visible = false; }); }
  spawnOne(index, count) {
    const missile = this.activate(); if (!missile) return; const origin = this.launcher.position.clone().add(new THREE.Vector3(0, 2.5, 0)); const targetPoint = this.target.position.clone().add(new THREE.Vector3(0, 2.1, 0));
    const forward = targetPoint.sub(origin).normalize(); const spread = new THREE.Vector3(this.random() * 2 - 1, this.random() * 1.4 - 0.7, this.random() * 2 - 1).normalize(); const launch = forward.clone().lerp(spread, this.config.launchConeAngle * (0.35 + this.random() * 0.45)).normalize();
    missile.root.position.copy(origin); missile.direction.copy(launch); missile.velocity.copy(launch).multiplyScalar(this.config.initialSpeed * (1 + (this.random() * 2 - 1) * this.config.speedVariation)); missile.previous.copy(origin); missile.age = -this.config.timingVariation * this.random(); missile.delay = index / Math.max(count, 1) * this.config.launchInterval; missile.life = this.config.lifetime; missile.sampleTimer = 0; missile.spread.copy(spread); missile.spread.y += (this.random() * 2 - 1) * 0.35; missile.spread.normalize(); missile.curlAxis.copy(new THREE.Vector3(this.random() * 2 - 1, this.random() * 2 - 1, this.random() * 2 - 1).normalize()); missile.curlAxis.applyAxisAngle(forward, (this.random() * 2 - 1) * this.config.curlAxisVariation); missile.curlAxis.normalize(); missile.cw = this.random() < this.config.clockwiseRatio ? 1 : -1; missile.curlStrength = this.config.curlStrength * (1 + (this.random() * 2 - 1) * this.config.curlStrengthVariation); missile.curlFrequency = this.config.curlFrequency * (1 + (this.random() * 2 - 1) * this.config.curlFrequencyVariation); missile.phase = this.random() * this.config.curlPhaseVariation; missile.turnRate = this.config.maxTurnRate * (1 + (this.random() * 2 - 1) * this.config.turnRateVariation); missile.history.forEach((point) => point.copy(origin));
  }
  steer(missile, delta) {
    const age01 = clamp01(missile.age / Math.max(missile.life, 0.01)); const launch = 1 - smooth(clamp01(age01 / 0.2)); const spreadFade = 1 - smooth(clamp01((age01 - 0.1) / Math.max(this.config.spreadDuration, 0.01))); const curlWindow = smooth(clamp01((age01 - this.config.curlStart) / Math.max(this.config.curlPeak - this.config.curlStart, 0.01))) * (1 - smooth(clamp01((age01 - this.config.curlPeak) / Math.max(this.config.curlEnd - this.config.curlPeak, 0.01)))); const terminal = smooth(clamp01((age01 - 0.6) / Math.max(this.config.terminalTurnRamp, 0.01))); const homing = smooth(clamp01((age01 - this.config.homingDelay) / Math.max(this.config.homingRampDuration, 0.01)));
    missile.targetVector.copy(this.target.position).add(new THREE.Vector3(0, 2.1, 0)).sub(missile.root.position).normalize(); missile.curl.copy(missile.direction).cross(missile.curlAxis).normalize().multiplyScalar(missile.cw); missile.curl.applyAxisAngle(missile.direction, Math.sin(missile.age * missile.curlFrequency + missile.phase) * 0.18);
    const noise = new THREE.Vector3(Math.sin(missile.age * this.config.noiseFrequency + missile.phase), Math.sin(missile.age * this.config.noiseFrequency * 1.17 + missile.phase * 1.3), Math.cos(missile.age * this.config.noiseFrequency * 0.83 + missile.phase)).multiplyScalar(this.config.noiseStrength);
    missile.desired.copy(missile.spread).multiplyScalar(this.config.spreadStrength * spreadFade * this.config.phaseSpread).addScaledVector(missile.curl, missile.curlStrength * curlWindow * this.config.phaseCurl).addScaledVector(missile.targetVector, this.config.homingStrength * homing * this.config.phaseHoming).add(noise); if (age01 < 0.24) missile.desired.addScaledVector(missile.direction, launch * 1.5 * this.config.phaseLaunch); missile.desired.normalize();
    const angle = missile.direction.angleTo(missile.desired); if (angle > 0.0001) { const axis = missile.direction.clone().cross(missile.desired).normalize(); missile.direction.applyAxisAngle(axis, Math.min(angle, (missile.turnRate + (this.config.terminalTurnRate - missile.turnRate) * terminal) * delta)); }
    const speedTarget = this.config.maxSpeed * (1 + (this.config.terminalSpeedMultiplier - 1) * terminal); missile.velocity.lerp(missile.direction.clone().multiplyScalar(speedTarget), clamp01(this.config.acceleration * delta / Math.max(speedTarget, 1))); missile.root.position.addScaledVector(missile.velocity, delta); missile.root.quaternion.setFromUnitVectors(new THREE.Vector3(0, 0, 1), missile.direction);
  }
  updateTrail(missile, delta) { missile.sampleTimer -= delta; if (missile.sampleTimer > 0) return; missile.sampleTimer = Math.max(0.005, this.config.trailSampleInterval); for (let i = missile.history.length - 1; i > 0; i -= 1) missile.history[i].copy(missile.history[i - 1]); missile.history[0].copy(missile.root.position); const count = Math.min(96, Math.max(2, Math.floor(this.config.trailPointCount))); const positions = missile.line.geometry.attributes.position.array; for (let i = 0; i < count; i += 1) { positions[i * 3] = missile.history[i].x; positions[i * 3 + 1] = missile.history[i].y; positions[i * 3 + 2] = missile.history[i].z; } missile.line.geometry.attributes.position.needsUpdate = true; missile.line.geometry.setDrawRange(0, this.config.trailEnabled ? count : 0); missile.line.visible = this.config.trailEnabled; }
  updateDebug(missile) { const show = this.config.showVelocityVectors || this.config.showDesiredDirection || this.config.showTargetVector || this.config.showSpreadVector || this.config.showCurlVector || this.config.showFinalSteeringVector; missile.arrows.forEach((arrow) => { arrow.visible = show && missile === this.active[0]; }); if (!show || missile !== this.active[0]) return; const vectors = [missile.velocity, missile.desired, missile.targetVector]; vectors.forEach((vector, index) => missile.arrows[index].setDirection(vector.clone().normalize()).setLength(2.5)); missile.arrows.forEach((arrow) => arrow.position.copy(missile.root.position)); }
  update(delta) { this.time += delta; if (this.volley) { this.volley.timer -= delta; while (this.volley.next < this.volley.count && this.volley.timer <= 0) { this.spawnOne(this.volley.next++, this.volley.count); this.volley.timer += Math.max(0.005, this.config.launchInterval); } if (this.volley.next >= this.volley.count) this.volley = null; } for (let i = this.active.length - 1; i >= 0; i -= 1) { const missile = this.active[i]; missile.age += delta; if (missile.age < missile.delay) continue; missile.life -= delta; missile.previous.copy(missile.root.position); this.steer(missile, delta); this.updateTrail(missile, delta); this.updateDebug(missile); const hit = missile.root.position.distanceTo(this.target.position.clone().add(new THREE.Vector3(0, 2, 0))) <= this.config.proximityFuseRadius; const out = Math.abs(missile.root.position.x) > 55 || Math.abs(missile.root.position.z) > 55 || missile.root.position.y < -4 || missile.root.position.y > 45; const direction = missile.root.position.clone().sub(missile.previous); this.raycaster.set(missile.previous, direction.normalize()); const blocked = direction.lengthSq() > 0.01 && this.raycaster.intersectObjects(this.obstacles, false).some((entry) => entry.distance <= direction.length()); if (hit) this.onHit?.(this.target, this.config.damage || 0); if (hit || out || blocked || missile.life <= 0) { this.release(missile); this.active.splice(i, 1); } } }
  get activeCount() { return this.active.length; }
  get trailVertices() { return this.active.reduce((total, missile) => total + (missile.line.geometry.drawRange.count || 0), 0); }
}
